import { Symmetry } from './symmetry.js';

// Global state
export const state = {
  canvas: null,
  ctx: null,
  images: [],
  selectedImage: null,
  isDragging: false,
  isResizing: false,
  isRotating: false,
  dragStart: { x: 0, y: 0 },
  resizeStart: { x: 0, y: 0, width: 0, height: 0 },
  rotateStart: { angle: 0, x: 0, y: 0 },
  selectionTool: 'pencil',
  zoomLevel: 1,
  panOffset: { x: 0, y: 0 },
  isPanning: false,
  panStart: { x: 0, y: 0 },
  undoStack: [],
  redoStack: [],
  isDrawing: false,
  drawingPaths: [],
  currentPath: [],
  drawingColor: '#ffffff',
  drawingSize: 3,
  eraserSize: 20,
  showGrid: true,
  gridSize: 50,
  gridType: 'square',
  gridColor: '#006400',
  backgroundColor: '#2d2d2d',
  spacebarDown: false,
  altKeyDown: false,
  previousTool: 'pencil',
  symmetry: new Symmetry(),
  isRightClickErasing: false,
  gridCells: [],
  lastGridCell: { x: null, y: null },
  lastGridMousePos: { x: null, y: null },
  selectionPath: [],
  selectedObjects: [],
  isMovingSelection: false,
  ghostOffset: { x: 0, y: 0 },
  isGhostVisible: false,
  gridTransformationMode: 'permanent', // 'permanent' or 'visual-only'
  showSymmetryLine: true,
  isCopying: false,
  gridBrushSize: 1
};

// DOM Elements
export const elements = {
  canvas: document.getElementById('drawingCanvas'),
  fileInput: document.getElementById('fileInput'),
  statusBar: document.getElementById('statusBar'),
  zoomInBtn: document.getElementById('zoomInBtn'),
  zoomOutBtn: document.getElementById('zoomOutBtn'),
  zoomResetBtn: document.getElementById('fitBtn'),
  toolButtons: document.querySelectorAll('.tool-btn'),
  clearCanvasBtn: document.getElementById('clearCanvasBtn'),
  saveBtn: document.getElementById('saveBtn'),

  loadBtn: document.getElementById('loadBtn'),
  uploadBtn: document.getElementById('uploadBtn'),
  zoomLevelDisplay: document.getElementById('zoomLevel'),
  toolStatus: document.getElementById('toolStatus'),
  posStatus: document.getElementById('posStatus'),
  gridColorPicker: document.getElementById('gridColorPicker'),
  gridSizeInput: document.getElementById('gridSizeInput'),
  backgroundColorPicker: document.getElementById('backgroundColorPicker'),
  brushSizeSlider: document.getElementById('brushSizeSlider'),
  brushSizeValue: document.getElementById('brushSizeValue'),
  brushColorPicker: document.getElementById('brushColorPicker'),
  swatchColorPicker: document.getElementById('swatchColorPicker'),
  eraserSizeSlider: document.getElementById('eraserSizeSlider'),
  eraserSizeValue: document.getElementById('eraserSizeValue'),
  gridBrushSizeSlider: document.getElementById('gridBrushSizeSlider'),
  gridBrushSizeValue: document.getElementById('gridBrushSizeValue'),
  symmetryBtn: document.getElementById('symmetryBtn'),
  gridTransformBtn: document.getElementById('gridTransformBtn'),
  colorPalette: document.getElementById('colorPalette'),
  app: document.getElementById('app'),
  togglePanelsBtn: document.getElementById('toggle-panels-btn'),
  mainMenu: document.getElementById('main-menu'),
  toggleTopToolbarCb: document.getElementById('toggle-top-toolbar-cb'),

  toggleLeftToolbarCb: document.getElementById('toggle-left-toolbar-cb'),
  toggleRightToolbarCb: document.getElementById('toggle-right-toolbar-cb'),
  symmetryPanel: document.getElementById('symmetry-panel'),

  symmetryModeBtns: document.querySelectorAll('.symmetry-mode-btn'),
  radialRayCountContainer: document.getElementById('radial-ray-count-container'),
  radialRayCountInput: document.getElementById('radial-ray-count')
};
